# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: Bash@3
  inputs:
    script: ls $(Agent.BuildDirectory)

# SSH
# Run shell commands or a script on a remote machine using SSH
- task: SSH@0
  inputs:
    sshEndpoint: CDAASAsiaSampleVM
    #runOptions: 'commands' # Options: commands, script, inline
    commands: ls 
    #scriptPath: # Required when runOptions == Script
    #inline: # Required when runOptions == Inline
    #args: # Optional
    #failOnStdErr: # Optional 

- task: SSH@0
  inputs:
    sshEndpoint: CDAASAsiaSampleVM
    commands: mkdir -p testfolder

# Copy Files Over SSH
# Copy files or build artifacts to a remote machine over SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: CDAASAsiaSampleVM
    sourceFolder: $(Agent.BuildDirectory)
    contents: '**/*.jar' 
    targetFolder: ~/testfolder
    #cleanTargetFolder: false # Optional
    #overwrite: true # Optional
    #failOnEmptySource: false # Optional
    #flattenFolders: false # Optional